apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wit-deployment
  labels: 
    app.kubernetes.io/part-of: application-1
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: wit-1
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "git@github.com:redhat-developer/topology-example.git"
    app.openshift.io/vcs-ref: "5a26937cdbb859aa786a73389ff7ef816ba9d63c"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/part-of: application-1
      app.kubernetes.io/name: nodejs
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: wit-1
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: application-1
        app.kubernetes.io/name: nodejs
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: wit-1
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - name: wit
          image: nginx:1.7.9
          ports:
            - containerPort: 80
